//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanySendOffers = new HashSet<CompanySendOffer>();
            this.Jobs = new HashSet<Job>();
            this.JobAlerts = new HashSet<JobAlert>();
            this.JobOffers = new HashSet<JobOffer>();
            this.CompanyLikeJobSeeker = new HashSet<JobSeeker>();
            this.CompanyLikeJobSeekerCV = new HashSet<JobSeeker>();
            this.JobSeekerLikeCompany = new HashSet<JobSeeker>();
            this.Ratings = new HashSet<Rating>();
        }

        public bool CheckDownTrend()
        {
            ApplyDAO applyDAO = new ApplyDAO();
            foreach (Job j in Jobs)
            {
                foreach (string str in applyDAO.FetchStatusApply(j.JobID))
                {
                    if (str.ToLower() == "approve")
                    {
                        return false;
                    }
                }
            }
            return true;
        }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CompanyType { get; set; }
        public string CompanySize { get; set; }
        public string Phonenumber { get; set; }
        public string WorkingTimeBegin { get; set; }
        public byte[] Avatar { get; set; }
        public string WorkingTimeEnd { get; set; }
        public string TaxIdentification { get; set; }
        public byte[] BusinessLicense { get; set; }
        public string Detail { get; set; }
        public string WebsiteLink { get; set; }
        public byte[] Like { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySendOffer> CompanySendOffers { get; set; }
        public virtual ImgCompany ImgCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAlert> JobAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker> CompanyLikeJobSeeker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker> CompanyLikeJobSeekerCV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker> JobSeekerLikeCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
