//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgCompany
    {
        public string companyID { get; set; }
        public byte[] ImgID1 { get; set; }
        public byte[] ImgID2 { get; set; }
        public byte[] ImgID3 { get; set; }
        public byte[] ImgID4 { get; set; }
        public byte[] ImgID5 { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
