//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public Interview()
        {

        }
        public Interview(string idJSeeker, string idJob, string timeInterview, DateTime dateInterview, string companyID)
        {
            this.IdJSeeker = idJSeeker;
            this.IdJob = idJob;
            this.TimeInterview = timeInterview;
            this.DateInterview = dateInterview;
            this.Status = "waiting";
            this.companyID = companyID;
            this.DateOffer = DateTime.Now;
        }
        public Interview(string idJSeeker, string idJob, string timeInterview, string status, DateTime dateInterview, string companyID)
        {
            this.IdJSeeker = idJSeeker;
            this.IdJob = idJob;
            this.TimeInterview = timeInterview;
            this.DateInterview = dateInterview;
            this.Status = status;
            this.companyID = companyID;
            this.DateOffer = DateTime.Now;
        }

        public string IdJSeeker { get; set; }
        public string IdJob { get; set; }
        public string TimeInterview { get; set; }
        public Nullable<System.DateTime> DateInterview { get; set; }
        public string Status { get; set; }
        public string companyID { get; set; }
        public System.DateTime DateOffer { get; set; }
    }
}
