//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Applies = new HashSet<Apply>();
            this.JobSeekerLikeJob = new HashSet<JobSeeker>();
        }
    
        public string JobID { get; set; }
        public string CompanyID { get; set; }
        public string JobName { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public string requirement { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string benefit { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string WorkingForm { get; set; }
        public string Like { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Applies { get; set; }
        public virtual Company Company { get; set; }
        public virtual JobSkill JobSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker> JobSeekerLikeJob { get; set; }
    }
}
