//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPreference
    {
        public string JobSeekerID { get; set; }
        public string Title { get; set; }
        public string Position { get; set; }
        public string CompanyType { get; set; }
        public string WorkingForm { get; set; }
        public string CompanySize { get; set; }
        public string Location { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Skill1 { get; set; }
        public string Skill2 { get; set; }
        public string Skill3 { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
