//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.Applies = new HashSet<Apply>();
            this.CompanySendOffers = new HashSet<CompanySendOffer>();
            this.JobAlerts = new HashSet<JobAlert>();
            this.JobOffers = new HashSet<JobOffer>();
            this.CompanyLikeJobSeeker = new HashSet<Company>();
            this.CompanyLikeJobSeekerCV = new HashSet<Company>();
            this.JobSeekerLikeCompany = new HashSet<Company>();
            this.Jobs = new HashSet<Job>();
            this.Ratings = new HashSet<Rating>();
        }
        public JobSeeker(string iD, string name, string email, string address, string phoneNumber, DateTime? dateOfBirth, string nationalID, byte[] avatar, string gender, CV cV)
        {
            ID = iD;
            Name = name;
            Email = email;
            Address = address;
            PhoneNumber = phoneNumber;
            DateOfBirth = dateOfBirth;
            NationalID = nationalID;
            Avatar = avatar;
            Gender = gender;
            CV = cV;
        }

        public bool CheckAge(DateTime birthDate)
        {
            int age = DateTime.Now.Year - birthDate.Year;

            // Check if the birthday has occurred this year
            if (DateTime.Now.Month < birthDate.Month || (DateTime.Now.Month == birthDate.Month && DateTime.Now.Day < birthDate.Day))
            {
                age--;
            }
            return age > 15;
        }


        public string ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string NationalID { get; set; }
        public byte[] Avatar { get; set; }
        public string Gender { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Applies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySendOffer> CompanySendOffers { get; set; }
        public virtual CV CV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAlert> JobAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        public virtual JobPreference JobPreference { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> CompanyLikeJobSeeker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> CompanyLikeJobSeekerCV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> JobSeekerLikeCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
